/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.DBClass;
import javax.swing.*;
import BackEnd.User;
import static java.lang.reflect.Array.set;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import BackEnd.System1;
import BackEnd.Employe;
/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {

   Connection con = null;
   
   private final System1 system;
    
    PreparedStatement pst = null;
    ResultSet rs = null;
     
    
    public Login(System1 system) {
       
       
        initComponents();
        this.system = system;
        //this.setResizable(false);
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JPanel = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PassText = new javax.swing.JPasswordField();
        Login1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("Utilizador:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel.setBackground(new java.awt.Color(255, 255, 255));
        JPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bem-Vindo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        JPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JPanel.setOpaque(false);

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setText("Entrar");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setText("Cancelar");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Utilizador");

        UserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Palavra-passe");

        Login1.setBackground(new java.awt.Color(255, 255, 255));
        Login1.setText("Adicionar utilizador");
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Por favor introduza o seus dados de acesso:");

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PassText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(UserText)))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Login1)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addComponent(Close)
                                .addGap(18, 18, 18)
                                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Close)
                    .addComponent(Login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(JPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 400, 270));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/yfcv.PNG"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 811, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void login(){
        if(UserText.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Introduza nome de utilizador");
            UserText.requestFocus();
        }
        
        if(PassText.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Introduza a palavra-passe");
            PassText.requestFocus();
        }
    }
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
     login();
     String username = UserText.getText();
     String password = PassText.getText();
     
       
           User u = new User (username, password);
           Employe e = new Employe();
           system.setEmp(e);
           system.setUser(u);
           system.getUser().add_user(username, password);
           system.getEmp().add_emp(system.getUser().getNum_emp());
        
           if(system.getUser().getType().equals("a")){
                  AdminMenu a= new AdminMenu(system);
           a.setVisible(true);}
            else    if(system.getUser().getType().equals("s")){
                  SecretaryMenu s= new SecretaryMenu(system);
           s.setVisible(true);}
           else    if(system.getUser().getType().equals("l")){
                  Lawyermenu l= new Lawyermenu(system);
           l.setVisible(true);}
      
           /*  String sql = "Select * from user where username=? and password=? ";
       try{
           
       Connection c = DBClass.getConnection();
      

           pst = c.prepareStatement(sql);
           
           pst.setString(1, UserText.getText());
           pst.setString(2, PassText.getText());
           ResultSet rs = pst.executeQuery();
           if(rs.next()){
           JOptionPane.showMessageDialog(null, "correct");
           
           String username = rs.getString("username");
           String password = rs.getString("password");
           String type = rs.getString("type");
           int num_emp = Integer.valueOf(rs.getString("num_emp"));
         
   
        
           else{
           JOptionPane.showMessageDialog(null, "incorrect");
           
           }
                   
       }
       catch(Exception e){
       JOptionPane.showMessageDialog(null,e);}*/
       dispose();
    }//GEN-LAST:event_LoginActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        system.end();
    }//GEN-LAST:event_CloseActionPerformed

    private void UserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextActionPerformed

    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
             String sql = "Select * from user ";
       try{
           
       Connection c = DBClass.getConnection();
      

           pst = c.prepareStatement(sql);
           

           ResultSet rs = pst.executeQuery();
           if(rs.wasNull()){
               
                 Userpage a= new Userpage(system);
           a.setVisible(true);  
               
                
               }}
       catch(Exception e){
       JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_Login1ActionPerformed

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginKeyPressed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton Login;
    private javax.swing.JButton Login1;
    private javax.swing.JPasswordField PassText;
    private javax.swing.JTextField UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
